"""Re-exports every model so Base.metadata is fully populated for Alembic autogenerate."""
from core.models.base import Base, new_id
from core.models.reference import AiPrompt, City, Configuration, Country, Role
from core.models.identity import AdminUser, AuditLog, Customer, CustomerSession, OtpChallenge
from core.models.addresses import CustomerAddress, RecentAddressSearch
from core.models.mart import (
    AiExecution,
    Cart,
    CartItem,
    MartCategory,
    MartOffer,
    MartProduct,
    MartStore,
    MartSubcategory,
    Order,
    OrderItem,
    RewardEntry,
    SupportTicket,
)
from core.models.express import (
    ExpressBooking,
    ExpressBookingItem,
    ExpressBookingTimeline,
    ExpressDeliveryPref,
    ExpressMoversCategory,
    ExpressMoversItem,
    ExpressMoversPricing,
    ExpressMoveType,
    ExpressPackageType,
    ExpressPricingRule,
    ExpressPromo,
    ExpressTimeSlot,
    ExpressVehicle,
    ExpressWeightTier,
    ModuleDriver,
)
from core.models.vendors import ModuleVendor, VendorDocument
from core.models.partners import APPLICATION_STATUSES, PartnerApplication

__all__ = [
    "Base",
    "new_id",
    "AiPrompt",
    "City",
    "Configuration",
    "Country",
    "Role",
    "AdminUser",
    "AuditLog",
    "Customer",
    "CustomerSession",
    "OtpChallenge",
    "CustomerAddress",
    "RecentAddressSearch",
    "AiExecution",
    "Cart",
    "CartItem",
    "MartCategory",
    "MartOffer",
    "MartProduct",
    "MartStore",
    "MartSubcategory",
    "Order",
    "OrderItem",
    "RewardEntry",
    "SupportTicket",
    "ExpressBooking",
    "ExpressBookingItem",
    "ExpressBookingTimeline",
    "ExpressDeliveryPref",
    "ExpressMoversCategory",
    "ExpressMoversItem",
    "ExpressMoversPricing",
    "ExpressMoveType",
    "ExpressPackageType",
    "ExpressPricingRule",
    "ExpressPromo",
    "ExpressTimeSlot",
    "ExpressVehicle",
    "ExpressWeightTier",
    "ModuleDriver",
    "ModuleVendor",
    "VendorDocument",
    "PartnerApplication",
    "APPLICATION_STATUSES",
]
