"""Re-exports every model so Base.metadata is fully populated for Alembic autogenerate."""
from core.models.base import Base, new_id
from core.models.reference import AiPrompt, City, Configuration, Country, Role
from core.models.identity import AdminUser, AuditLog, Customer, CustomerSession, OtpChallenge
from core.models.addresses import CustomerAddress, RecentAddressSearch
from core.models.mart import (
    AiExecution,
    Cart,
    CartItem,
    MartCategory,
    MartOffer,
    MartProduct,
    MartStore,
    MartSubcategory,
    Order,
    OrderItem,
    RewardEntry,
    SupportTicket,
)
from core.models.express import (
    ExpressBooking,
    ExpressBookingItem,
    ExpressBookingTimeline,
    ExpressDeliveryPref,
    ExpressMoversCategory,
    ExpressMoversItem,
    ExpressMoversPricing,
    ExpressMoveType,
    ExpressPackageType,
    ExpressPricingRule,
    ExpressPromo,
    ExpressTimeSlot,
    ExpressVehicle,
    ExpressWeightTier,
    ModuleDriver,
)
from core.models.vendors import ModuleVendor, VendorDocument
from core.models.partners import (
    APPLICATION_STATUSES, Partner, PartnerApplication, Warehouse,
    WarehouseAisle, WarehouseBin, WarehouseRack, WarehouseShelf, WarehouseZone,
    WAREHOUSE_STATUSES, WAREHOUSE_STATUS_OPERATIONAL, WAREHOUSE_STATUS_MANAGEABLE,
)
from core.models.partner_commerce import (
    PARTNER_ORDER_STATUSES, PARTNER_WALLET_TX_KINDS,
    PartnerOrder, PartnerProduct, PartnerWallet, PartnerWalletTxn,
)
from core.models.partner_staff import (
    PARTNER_STAFF_ROLES, PartnerStaff, PartnerStaffAuditLog,
    PartnerStaffStoreAssignment,
)
from core.models.catalog_inventory import (
    PARTNER_PRODUCT_APPROVAL_STATUSES, STOCK_MOVEMENT_KINDS,
    MartBrand, PartnerInventory, PartnerProductLocation, PartnerStockMovement,
)
from core.models.inventory_ops import (
    RECEIPT_STATUSES, RECEIPT_SOURCES, COUNT_STATUSES, COUNT_SCOPES,
    PartnerReceipt, PartnerReceiptItem,
    PartnerStockCount, PartnerStockCountLine,
)
from core.models.replenishment import (
    REPLENISHMENT_STATUSES, REPLENISHMENT_SOURCES, PartnerReplenishment,
)

__all__ = [
    "Base",
    "new_id",
    "AiPrompt",
    "City",
    "Configuration",
    "Country",
    "Role",
    "AdminUser",
    "AuditLog",
    "Customer",
    "CustomerSession",
    "OtpChallenge",
    "CustomerAddress",
    "RecentAddressSearch",
    "AiExecution",
    "Cart",
    "CartItem",
    "MartCategory",
    "MartOffer",
    "MartProduct",
    "MartStore",
    "MartSubcategory",
    "Order",
    "OrderItem",
    "RewardEntry",
    "SupportTicket",
    "ExpressBooking",
    "ExpressBookingItem",
    "ExpressBookingTimeline",
    "ExpressDeliveryPref",
    "ExpressMoversCategory",
    "ExpressMoversItem",
    "ExpressMoversPricing",
    "ExpressMoveType",
    "ExpressPackageType",
    "ExpressPricingRule",
    "ExpressPromo",
    "ExpressTimeSlot",
    "ExpressVehicle",
    "ExpressWeightTier",
    "ModuleDriver",
    "ModuleVendor",
    "VendorDocument",
    "PartnerApplication",
    "Partner",
    "Warehouse",
    "APPLICATION_STATUSES",
    "WarehouseZone",
    "WarehouseAisle",
    "WarehouseRack",
    "WarehouseShelf",
    "WarehouseBin",
    "PartnerProduct",
    "PartnerOrder",
    "PartnerWallet",
    "PartnerWalletTxn",
    "PartnerStaff",
    "PartnerStaffAuditLog",
    "PartnerStaffStoreAssignment",
    "PARTNER_ORDER_STATUSES",
    "PARTNER_WALLET_TX_KINDS",
    "PARTNER_STAFF_ROLES",
    "WAREHOUSE_STATUSES",
    "WAREHOUSE_STATUS_OPERATIONAL",
    "WAREHOUSE_STATUS_MANAGEABLE",
    "MartBrand",
    "PartnerInventory",
    "PartnerProductLocation",
    "PartnerStockMovement",
    "PARTNER_PRODUCT_APPROVAL_STATUSES",
    "STOCK_MOVEMENT_KINDS",
    "PartnerReceipt", "PartnerReceiptItem",
    "PartnerStockCount", "PartnerStockCountLine",
    "RECEIPT_STATUSES", "RECEIPT_SOURCES", "COUNT_STATUSES", "COUNT_SCOPES",
    "PartnerReplenishment", "REPLENISHMENT_STATUSES", "REPLENISHMENT_SOURCES",
]
