"""initial schema

Revision ID: 3200d0b5b23c
Revises: 
Create Date: 2026-07-25 20:57:41.031997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3200d0b5b23c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('admin_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'admin', 'super_admin', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_admin_users_email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_kind', sa.String(), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_created_at', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_target_id', 'audit_logs', ['target_id'], unique=False)
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('currency_symbol', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('phone_code', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('production_visible', sa.Boolean(), nullable=False),
    sa.Column('min_order', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('free_delivery_over', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('delivery_eta_min', sa.String(), nullable=True),
    sa.Column('service_radius_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('express_delivery_prefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_express_delivery_prefs_code')
    )
    op.create_table('express_move_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_express_move_types_code')
    )
    op.create_table('express_movers_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_express_movers_categories_code')
    )
    op.create_table('express_movers_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_code', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('labour_required', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category_code', 'country', name='uq_express_movers_items_natural_key')
    )
    op.create_table('express_weight_tiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_express_weight_tiers_code')
    )
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_challenges_phone_created_at', 'otp_challenges', ['phone', 'created_at'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ai_prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_ai_prompts_name')
    )
    op.create_table('cities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country', name='uq_cities_name_country')
    )
    op.create_table('configurations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'module', 'country', name='uq_configurations_scope_module_country')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('customer', 'admin', 'super_admin', name='user_role'), nullable=False),
    sa.Column('auth_providers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('referred_by_customer_id', sa.String(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['referred_by_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_customers_email'),
    sa.UniqueConstraint('phone', name='uq_customers_phone'),
    sa.UniqueConstraint('referral_code', name='uq_customers_referral_code')
    )
    op.create_table('express_movers_pricing',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('price_per_km', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transport_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('packing_per_item', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loading_unloading_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loading_per_item', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('labour_per_mover', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('floor_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stair_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('toll_permits', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('value_per_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('insurance_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('insurance_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxes_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('advance_flat', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('advance_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', name='uq_express_movers_pricing_country')
    )
    op.create_table('express_package_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'country', name='uq_express_package_types_code_country')
    )
    op.create_table('express_pricing_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('vehicle_code', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_fare', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_per_km', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_per_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('waiting_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('peak_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('night_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('service_fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('insurance_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('insurance_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxes_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_express_pricing_rules_active', 'express_pricing_rules', ['country', 'vehicle_code'], unique=True, postgresql_where='active')
    op.create_table('express_promos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('percent','flat')", name='ck_express_promos_kind'),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'country', name='uq_express_promos_code_country')
    )
    op.create_table('express_time_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('window', sa.String(), nullable=True),
    sa.Column('surcharge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'country', name='uq_express_time_slots_code_country')
    )
    op.create_table('express_vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('max_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('eta_min_min', sa.Integer(), nullable=True),
    sa.Column('eta_min_max', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'country', name='uq_express_vehicles_code_country')
    )
    op.create_table('mart_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_fr', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'country', name='uq_mart_categories_slug_country')
    )
    op.create_table('mart_offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'country', name='uq_mart_offers_title_country')
    )
    op.create_table('mart_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category_slug', sa.String(), nullable=True),
    sa.Column('subcategory_slug', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('was_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('currency_symbol', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country', 'module', name='uq_mart_products_name_country_module')
    )
    op.create_index('ix_mart_products_brand_trgm', 'mart_products', ['brand'], unique=False, postgresql_using='gin', postgresql_ops={'brand': 'gin_trgm_ops'})
    op.create_index('ix_mart_products_category_slug_country', 'mart_products', ['category_slug', 'country'], unique=False)
    op.create_index('ix_mart_products_name_trgm', 'mart_products', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('mart_stores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('eta', sa.String(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country', name='uq_mart_stores_name_country')
    )
    op.create_table('module_drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('vehicle_reg', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('current_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('active_booking_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', 'suspended', name='driver_status'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', 'module', name='uq_module_drivers_phone_module')
    )
    op.create_index('ix_module_drivers_dispatch', 'module_drivers', ['module', 'country', 'vehicle_type', 'status', 'is_available'], unique=False)
    op.create_table('module_vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'active', 'rejected', 'suspended', name='vendor_status'), nullable=False),
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'module', name='uq_module_vendors_name_module')
    )
    op.create_index('ix_module_vendors_module_status', 'module_vendors', ['module', 'status'], unique=False)
    op.create_table('ai_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_carts_one_active_per_customer', 'carts', ['customer_id'], unique=True, postgresql_where="status = 'active'")
    op.create_table('customer_addresses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('line1', sa.String(), nullable=False),
    sa.Column('line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_customer_addresses_one_default', 'customer_addresses', ['customer_id'], unique=True, postgresql_where='is_default AND deleted_at IS NULL')
    op.create_table('customer_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token', name='uq_customer_sessions_token')
    )
    op.create_table('express_bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('booking_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'succeeded', 'authorized', 'failed', 'advance_pending', 'paid', name='payment_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('currency_symbol', sa.String(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('scheduled_for', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('vehicle_code', sa.String(), nullable=True),
    sa.Column('pickup_line1', sa.String(), nullable=True),
    sa.Column('pickup_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pickup_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pickup_formatted_address', sa.String(), nullable=True),
    sa.Column('pickup_place_id', sa.String(), nullable=True),
    sa.Column('pickup_landmark', sa.String(), nullable=True),
    sa.Column('pickup_building', sa.String(), nullable=True),
    sa.Column('pickup_city', sa.String(), nullable=True),
    sa.Column('pickup_country', sa.String(), nullable=True),
    sa.Column('drop_line1', sa.String(), nullable=True),
    sa.Column('drop_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('drop_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('drop_formatted_address', sa.String(), nullable=True),
    sa.Column('drop_place_id', sa.String(), nullable=True),
    sa.Column('drop_landmark', sa.String(), nullable=True),
    sa.Column('drop_building', sa.String(), nullable=True),
    sa.Column('drop_city', sa.String(), nullable=True),
    sa.Column('drop_country', sa.String(), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('receiver_phone', sa.String(), nullable=True),
    sa.Column('receiver_alt_phone', sa.String(), nullable=True),
    sa.Column('receiver_building', sa.String(), nullable=True),
    sa.Column('receiver_landmark', sa.String(), nullable=True),
    sa.Column('receiver_notes', sa.String(), nullable=True),
    sa.Column('receiver_preferences', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('package_type', sa.String(), nullable=True),
    sa.Column('package_weight_range', sa.String(), nullable=True),
    sa.Column('package_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('package_notes', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('price_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('driver_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('driver_location_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('driver_location_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('move_type', sa.String(), nullable=True),
    sa.Column('movers_pickup_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('movers_drop_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quote_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('advance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remaining', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('time_slot_code', sa.String(), nullable=True),
    sa.Column('labour_movers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("booking_type IN ('parcel','movers')", name='ck_express_bookings_booking_type'),
    sa.CheckConstraint("status IN ('searching','driver_assigned','arriving','picked_up','in_transit','delivered','cancelled','confirmed')", name='ck_express_bookings_status'),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['module_drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref', name='uq_express_bookings_ref')
    )
    op.create_index('ix_express_bookings_customer_module', 'express_bookings', ['customer_id', 'module'], unique=False)
    op.create_index('ix_express_bookings_customer_status', 'express_bookings', ['customer_id', 'status'], unique=False)
    # Deferred: module_drivers.active_booking_id <-> express_bookings is a mutual FK
    # reference; this side is added after both tables exist.
    op.create_foreign_key(
        'fk_module_drivers_active_booking_id',
        'module_drivers', 'express_bookings',
        ['active_booking_id'], ['id'],
    )
    op.create_table('mart_subcategories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_fr', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mart_categories.id'], ),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'category_id', name='uq_mart_subcategories_slug_category')
    )
    op.create_table('recent_address_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recent_searches_customer_last_used', 'recent_address_searches', ['customer_id', 'last_used_at'], unique=False)
    op.create_index('uq_recent_searches_by_address', 'recent_address_searches', ['customer_id', 'formatted_address'], unique=True, postgresql_where='place_id IS NULL')
    op.create_index('uq_recent_searches_by_place_id', 'recent_address_searches', ['customer_id', 'place_id'], unique=True, postgresql_where='place_id IS NOT NULL')
    op.create_table('vendor_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['module_vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['mart_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', 'module', name='uq_cart_items_cart_product_module')
    )
    op.create_table('express_booking_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['express_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['express_movers_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('express_booking_timeline',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['express_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'preparing', 'picked_up', 'on_the_way', 'delivered', 'cancelled', name='order_status'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('points_redeemed', sa.Integer(), nullable=False),
    sa.Column('points_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_address_id', sa.String(), nullable=True),
    sa.Column('delivery_slot_id', sa.String(), nullable=True),
    sa.Column('delivery_slot_label', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'succeeded', 'authorized', 'failed', 'advance_pending', 'paid', name='payment_status'), nullable=False),
    sa.Column('payment_provider', sa.String(), nullable=True),
    sa.Column('payment_provider_ref', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_comment', sa.String(), nullable=True),
    sa.Column('rated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['source_address_id'], ['customer_addresses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_orders_number')
    )
    op.create_index('ix_orders_customer_deleted_created', 'orders', ['customer_id', 'deleted_at', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['mart_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('earned','redeemed')", name='ck_reward_entries_kind'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reward_entries_customer_created', 'reward_entries', ['customer_id', 'created_at'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('order', 'delivery', 'wallet', 'payment', 'property', 'vehicle', 'account', 'other', name='ticket_category'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='ticket_priority'), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticket_status'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_support_tickets_number')
    )
    op.create_index('ix_support_tickets_customer_deleted_created', 'support_tickets', ['customer_id', 'deleted_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_tickets_customer_deleted_created', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_reward_entries_customer_created', table_name='reward_entries')
    op.drop_table('reward_entries')
    op.drop_table('order_items')
    op.drop_index('ix_orders_customer_deleted_created', table_name='orders')
    op.drop_table('orders')
    op.drop_table('express_booking_timeline')
    op.drop_table('express_booking_items')
    op.drop_table('cart_items')
    op.drop_table('vendor_documents')
    op.drop_index('uq_recent_searches_by_place_id', table_name='recent_address_searches', postgresql_where='place_id IS NOT NULL')
    op.drop_index('uq_recent_searches_by_address', table_name='recent_address_searches', postgresql_where='place_id IS NULL')
    op.drop_index('ix_recent_searches_customer_last_used', table_name='recent_address_searches')
    op.drop_table('recent_address_searches')
    op.drop_table('mart_subcategories')
    op.drop_constraint('fk_module_drivers_active_booking_id', 'module_drivers', type_='foreignkey')
    op.drop_index('ix_express_bookings_customer_status', table_name='express_bookings')
    op.drop_index('ix_express_bookings_customer_module', table_name='express_bookings')
    op.drop_table('express_bookings')
    op.drop_table('customer_sessions')
    op.drop_index('uq_customer_addresses_one_default', table_name='customer_addresses', postgresql_where='is_default AND deleted_at IS NULL')
    op.drop_table('customer_addresses')
    op.drop_index('uq_carts_one_active_per_customer', table_name='carts', postgresql_where="status = 'active'")
    op.drop_table('carts')
    op.drop_table('ai_executions')
    op.drop_index('ix_module_vendors_module_status', table_name='module_vendors')
    op.drop_table('module_vendors')
    op.drop_index('ix_module_drivers_dispatch', table_name='module_drivers')
    op.drop_table('module_drivers')
    op.drop_table('mart_stores')
    op.drop_index('ix_mart_products_name_trgm', table_name='mart_products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_mart_products_category_slug_country', table_name='mart_products')
    op.drop_index('ix_mart_products_brand_trgm', table_name='mart_products', postgresql_using='gin', postgresql_ops={'brand': 'gin_trgm_ops'})
    op.drop_table('mart_products')
    op.drop_table('mart_offers')
    op.drop_table('mart_categories')
    op.drop_table('express_vehicles')
    op.drop_table('express_time_slots')
    op.drop_table('express_promos')
    op.drop_index('uq_express_pricing_rules_active', table_name='express_pricing_rules', postgresql_where='active')
    op.drop_table('express_pricing_rules')
    op.drop_table('express_package_types')
    op.drop_table('express_movers_pricing')
    op.drop_table('customers')
    op.drop_table('configurations')
    op.drop_table('cities')
    op.drop_table('ai_prompts')
    op.drop_table('roles')
    op.drop_index('ix_otp_challenges_phone_created_at', table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_table('express_weight_tiers')
    op.drop_table('express_movers_items')
    op.drop_table('express_movers_categories')
    op.drop_table('express_move_types')
    op.drop_table('express_delivery_prefs')
    op.drop_table('countries')
    op.drop_index('ix_audit_logs_target_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
    # Shared Postgres ENUM types aren't dropped by drop_table (they may be reused
    # across tables), so remove them explicitly once nothing references them.
    op.execute("DROP TYPE IF EXISTS ticket_status")
    op.execute("DROP TYPE IF EXISTS ticket_priority")
    op.execute("DROP TYPE IF EXISTS ticket_category")
    op.execute("DROP TYPE IF EXISTS vendor_status")
    op.execute("DROP TYPE IF EXISTS driver_status")
    op.execute("DROP TYPE IF EXISTS payment_status")
    op.execute("DROP TYPE IF EXISTS order_status")
    op.execute("DROP TYPE IF EXISTS user_role")
